[project]
name = "TheWorld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diffusers>=0.34.0",
    "peft>=0.17.0",
    "torch>=2.8.0",
    "torchaudio>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.56.2",
]

[dependency-groups]
dev = [
    "black>=24.0.0",
]

[tool.black]
line-length = 120
target-version = ["py312"]
