[project]
name = "TheWorld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "diffusers>=0.34.0",
    "peft>=0.15.0",
    "torch",
    "torchaudio",
    "torchvision",
    "transformers>=4.56.0",
]

[dependency-groups]
dev = [
    "black>=24.0.0",
]

[tool.black]
line-length = 120
target-version = ["py312"]
